version: '2'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    links:
      - postgres
      - redis
    environment:
      SMTP_USER:
      SMTP_SERVER:
      SMTP_PASSWORD:
    command: 'pipenv run worker'

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      DEBUG: 1
    links:
      - postgres
      - redis
    command: 'pipenv run webapp'
